#server:
#  port: 8080
#
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: employeeModule
#        uri: http://localhost:8081/
#        predicates:
#        - Path=/employee/**
#      - id: consumerModule
#        uri: http://localhost:8082/
#        predicates:
#        - Path=/consumer/**
#

server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: studentService
          uri: http://localhost:8081/student-service
          predicates:
            - Path=/student-service/**
        - id: feeService
          uri: http://localhost:8082/fee-service
          predicates:
            - Path=/fee-service/**